server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  cloud:
    gateway:
      routes:
        - id: User-Service
          uri: lb://User-Service
          predicates:
            - Path=/login/**,/logout/**
        - id: Storage-Server
          uri: lb://Storage-Server
          predicates:
            - Path=/file/**,/list/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:8081"
            allowCredentials: true
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - OPTIONS
              - DELETE