server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      format_sql: true
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/cloud_db
    username: postgres
    password: nhfnfnf1
    driverClassName: org.postgresql.Driver
